### PR TITLE
Fix Authentication token expiration check

### LINKED ISSUE #184: 401 Unauthorized access | Check PAT token and GitHub permissions.
Image

Hi! [@martedesco](https://github.com/martedesco) & [@karpikpl](https://github.com/karpikpl)
I just updated the dashboard from v1.9 to v2.0.3 and am facing an issue with unauthorized access. Nothing has changed since we had access to all metrics prior to the version update.

We are using the GitHub app for authentication, and this error is visible to the organization or enterprise owners who didn't have an issue before. I also verified that the pod with the application has environment variables with accurate keys and values. 

Is there a document with all the updates and changes made between v1.9 and v2.0.3? While updating the image version, I encountered other small issues, such as the new callback format.

Let me know if any other information is needed for a better investigation!

### PR DESCRIPTION
**Pull request by tonglil**
Closes #184 and #190.

Throw an error if a token does not exist when building the Authorization header.

When using the GitHub OAuth app to authenticate, this is the `secure` object:
```
secure {
  tokens: {
    access_token: 'ghu_xxxxxxxxxxxxxxxxxxx',
    token_type: 'bearer',
    scope: ''
  },
  expires_at: null
}
```

`expires_at` is null, so it always calls `buildHeaders` with an empty string (which doesn't make sense).

Removed this erroneous code and throw an error if the header is being built without a token.

### CODE REVIEW

File: server/modules/authentication.ts [hunk 1]
```diff
@@ -29,17 +29,14 @@ export async function authenticateAndGetGitHubHeaders(event: H3Event<EventHandle
...
 
-    // check if token is expired and get new one
-    if (secure && secure.expires_at < new Date(Date.now() - 30 * 1000)) {
-        // Token is expired or about to expire within 30 seconds
-        // we could refresh but unlikely dashboard is used for long periods
-        return buildHeaders('');
-    }
-
-    return buildHeaders(secure?.tokens.access_token || '');
+    return buildHeaders(secure?.tokens?.access_token || '');
```
Comment (github-sebastien-boulet) [inline server/modules/authentication.ts:39]: 👍

**Comment by karpikpl** [comment]
Thanks for the PR, let me review and test.
I never run it with OAuth app

File: server/modules/authentication.ts (hunk 1 above)
Comment (karpikpl) [inline server/modules/authentication.ts:39]:
```suggestion
    // check if token is expired and get new one
    if (secure?.expires_at && secure.expires_at < new Date(Date.now() - 30 * 1000)) {
        // Token is expired or about to expire within 30 seconds
        // we could refresh but unlikely dashboard is used for long periods
        return buildHeaders('');
    }

    return buildHeaders(secure?.tokens?.access_token || '');
```
